### PR TITLE
Markdown feature added

### PR DESCRIPTION
**Pull request by kkothari2001**

### CODE REVIEW

**Comment by kkothari2001** [comment]
I solved the merge conflicts @VedantParanjape , pls check once, after that I'll make small changes in CSS before merging

**Comment by VedantParanjape** [comment]
>  I solved the merge conflicts @VedantParanjape , pls check once, after that I'll make small changes in CSS before merging

LGTM !

**Comment by kkothari2001** [comment]
image
image

**Comment by VedantParanjape** [comment]
> a.
> image
> b.
> image
> 
> 
> @VedantParanjape 

Looks nice.

**Comment by kkothari2001** [comment]
There is an issue with an empty line (newline) appearing at the end of every title and paragraph. But ig we can ignore that for now and focus on releasing this feature

**Comment by kkothari2001** [comment]
Merging

**Pull request merged**
