### PR TITLE
Added a Section to Display what's going on in SRA, to resolve issue #47

### PR DESCRIPTION
**Pull request by sarrah-basta**
Added a sub-section named /aboutUsCurrent in the AboutUs section on the website's homepage. This sub-section displays data that can be uploaded in data/aboutus.js in the form of an array, as an unordered list in two columns, resolving Issue #47

### CODE REVIEW

**Comment by kkothari2001** [comment]
@sarrah-basta Please put up the latest screenshots here.

**Comment by kkothari2001** [comment]
@gautam-dev-maker @VedantParanjape  once Sarrah puts up the screenshots, let us discuss what to add in the data here.

**Comment by sarrah-basta** [comment]
> @sarrah-basta Please put up the latest screenshots here.

image

How the added section would look on the website.

image
How the data would have to be uploaded, i.e. in two seperate arrays for left and right.

**Comment by VedantParanjape** [comment]
@gautam-dev-maker Let them know what content needs to be added.

**Comment by gautam-dev-maker** [comment]
As discussed on personal Group, we need to include every events from Mario 2020, i.e.
1) Mario 2020
2) Algocon 2020
3) Eklavya 2020
4) practice Assignment Solving in October
5) SAC 2020
5) WallE 2021
6) Pixels 2021
7) Algocon 2021
8) Mario 2021
9) Eklavya 2021
10) SAC 2021
11) WallE 2022

**Comment by VedantParanjape** [comment]
@sarrah-basta Please get this done.

**Comment by sarrah-basta** [comment]
image

The commits made with said data would look on the website as such.

**Comment by kkothari2001** [comment]
@sarrah-basta how does this work out in smaller screensizes?

**Comment by VedantParanjape** [comment]
Is this PR dead ? Can it be worked on now ? @kkothari2001 @sarrah-basta

**Comment by sarrah-basta** [comment]
> @sarrah-basta how does this work out in smaller screensizes?

I can work on it if this is still required, as @kkothari2001 had asked about this, the two columns do not look that good on a smaller screen size. So one idea is to make it such that when a screen size drops below a certain width, we could use one column instead of two ?

Would doing this using window.size be okay ?

**Comment by kkothari2001** [comment]
> > @sarrah-basta how does this work out in smaller screensizes?
> 
> I can work on it if this is still required, as @kkothari2001 had asked about this, the two columns do not look that good on a smaller screen size. So one idea is to make it such that when a screen size drops below a certain width, we could use one column instead of two ?
> 
> Would doing this using window.size be okay ?

@sarrah-basta There's a scripts folder, which has a window size hook. See how that is used in the navbar component, and apply it to this component. This is useful for when we want dynamic behaviour with changing window sizes.

**Comment by amanchhaparia** [comment]
@Dhruv454000, is still work going on this PR?

**Comment by kkothari2001** [comment]
@amanchhaparia I don't like the content that's going into this PR.

Let's just stick to updating notifications down below. There's already quite a bit of redundancy about the info on the website, with seperate lists for current projects, current activities, internships etc.

With your approval I'll close this PR.

**Pull request closed without merging**
