### PR TITLE
University Reach and Corporates updated

### PR DESCRIPTION
**Pull request by sameergupta4873**
University admits to University Reach, added Edinburgh University, checked the previous universities in the previous commits  and added Apple as corporate.
Screenshot 2022-11-07 at 11 27 04 PM

### CODE REVIEW

**Review by kkothari2001 — CHANGES_REQUESTED** [review]
I'm including changes from the old commit here:

Changes in Industrial Reach:
Move Apple and AMD after Espressif, move Airpix to the bottom

Changes in University Reach (make them in order):
- Move EPFL after CMU
- Move Edinburgh after EPFL
- Add Princeton after Edinburgh
- Add Columbia after Princeton
- Move Worchester Polytechnique after USC
- Add IITKGP after IITB

**Comment by kkothari2001** [comment]
@sameergupta4873 

Just a quick comment:
Whenever you're creating a PR, first update your fork's main with our main, then create a branch in your repo. We don't want duplicate commits to affect our code.

I'll review this in some time.

**Comment by sameergupta4873** [comment]
> I'm including changes from the old commit here:
> 
> Changes in Industrial Reach: Move Apple and AMD after Espressif, move Airpix to the bottom
> 
> Changes in University Reach (make them in order):
> 
> * Move EPFL after CMU
> * Move Edinburgh after EPFL
> * Add Princeton after Edinburgh
> * Add Columbia after Princeton
> * Move Worchester Polytechnique after USC
> * Add IITKGP after IITB
> 
> cc @VedantParanjape (please point out if there are any issues with this order)

The Above Mentioned changes had been done, Please review once @kkothari2001 
Screenshot 2022-11-08 at 10 58 18 AM

**Comment by VedantParanjape** [comment]
> I'm including changes from the old commit here:
> 
> Changes in Industrial Reach:
> Move Apple and AMD after Espressif, move Airpix to the bottom
> 
> Changes in University Reach (make them in order):
> - Move EPFL after CMU
> - Move Edinburgh after EPFL
> - Add Princeton after Edinburgh
> - Add Columbia after Princeton
> - Move Worchester Polytechnique after USC
> - Add IITKGP after IITB
> 
> cc @VedantParanjape (please point out if there are any issues with this order)

lgtm !

**Review by kkothari2001 — APPROVED** [review]
LGTM

**Pull request merged**
